### ISSUE TITLE
Installation via Stack

### ISSUE THREAD

**Issue by adithyaov** [raaz-crypto/raaz#378]
raaz requires: >=4.6 && <4.11
The latest is which is used by stack is base-4.11.1.0
ignoring that constraint and proceeding the following error occurs.

![screenshot from 2018-09-29 16-28-07](https://user-images.githubusercontent.com/17845944/46245140-d825bd80-c406-11e8-9c79-c29ba6bc6ff3.png)

Please help me with the installation of this package via stack.

Thanks!

**Comment by piyush-kurur** [comment]
If you want to use stack with raaz (0.2.0) you will need to use an older lts (8.6 for example). 

My prefered method of development is `cabal install (version >= 8.2)`  with the `new-build` commands <https://www.haskell.org/cabal/users-guide/nix-local-build-overview.html> instead of 
stack.  This is particularly true if you want to use newer versions of raaz ( To be release, try the version from github right now) because of the use of backpack to solve certain 
design issues in the library.  Stack support should not be difficult once they start supporting backpack (commercialhaskell/stack#2540).

**Comment by adithyaov** [comment]
I agree, cabal new-* seems to work pretty amazing. Also, stack with the snapshot of lts-8.6 seems to work fine. Thank you for the help.
